# Generated by Django 4.0.2 on 2022-02-20 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default=None, help_text='Hostname', max_length=50, unique=True, verbose_name='Hostname')),
                ('device_type', models.CharField(default=None, help_text='Device Model', max_length=50, verbose_name='Model')),
                ('manufacturer', models.CharField(default=None, help_text='Device Manufacturer', max_length=50, verbose_name='Manufacturer')),
                ('serial_number', models.CharField(default=None, help_text='Serial Number', max_length=50, unique=True, verbose_name='Serial Number')),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventory',
                'db_table': 'inventory',
            },
        ),
    ]
