# Generated by Django 4.0.2 on 2022-02-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Documentation name.', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Documentation description.', null=True, verbose_name='Description')),
                ('url', models.URLField(help_text='Documentation URL.', max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Documentation',
                'verbose_name_plural': 'Documentation',
                'db_table': 'documentation',
            },
        ),
    ]
