# Generated by Django 4.0.2 on 2022-02-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_remove_documentation_name_remove_documentation_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='obj_url',
            field=models.URLField(default='', help_text='Objective Reference.', max_length=255, verbose_name='URL'),
        ),
    ]
