# Generated by Django 4.0.2 on 2022-02-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_alter_documentation_obj_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='category',
            field=models.CharField(default='', help_text='Documentation Category.', max_length=255, verbose_name='Category'),
        ),
    ]
