# Generated by Django 4.0.2 on 2022-02-20 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='created_by',
            field=models.ForeignKey(help_text='Created By', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='description',
            field=models.TextField(help_text='Ticket Description', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='id',
            field=models.IntegerField(help_text='Ticket ID', primary_key=True, serialize=False, unique=True, verbose_name='Ticket ID'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last Updated', verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(help_text='Ticket Status', max_length=100, verbose_name='Status'),
        ),
    ]
